{
 "title": "energy_consumption",
 "time": { "from": "2016-01-01T20:00:00.000Z", "to": "2016-03-19T21:00:00.000Z" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Energy consumption - Average Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('day', w.timestamp) AS \"time\",\n  AVG(w.air_temperature) AS \"Average Temperature\",\n  AVG(sd.meter_reading) AS \"Average Energy Consumption\"\nFROM\n  weather_data w\nJOIN\n  sensor_data sd ON date_trunc('day', w.timestamp) = date_trunc('day', sd.timestamp)\nGROUP BY\n  date_trunc('day', w.timestamp)\nORDER BY\n  \"time\";\n"
    }
   ]
  },
  {
   "title": "Average consumption for Area 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', sd.timestamp) AS \"time\",\n  AVG(sd.meter_reading) AS \"Total Consumption\"\nFROM\n  sensor_data sd\nJOIN\n  buildings b ON sd.building_id = b.building_id\nWHERE\n  b.site_id = 1\nGROUP BY\n  date_trunc('hour', sd.timestamp), b.site_id\nORDER BY\n  \"time\";\n"
    }
   ]
  },
  {
   "title": "average consumption for area 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', sd.timestamp) AS \"time\",\n  AVG(sd.meter_reading) AS \"Total Consumption\"\nFROM\n  sensor_data sd\nJOIN\n  buildings b ON sd.building_id = b.building_id\nWHERE\n  b.site_id = 2\nGROUP BY\n  date_trunc('hour', sd.timestamp), b.site_id\nORDER BY\n  \"time\";\n"
    }
   ]
  },
  {
   "title": "Average consumption per building",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  CAST(building_id AS text) AS \"Building ID\",\n  AVG(meter_reading) AS \"Average Consumption\"\nFROM\n  sensor_data\nGROUP BY\n  building_id\nORDER BY\n  CAST(building_id AS integer); \n"
    }
   ]
  },
  {
   "title": "Average consumption for Area 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', sd.timestamp) AS \"time\",\n  AVG(sd.meter_reading) AS \"Total Consumption\"\nFROM\n  sensor_data sd\nJOIN\n  buildings b ON sd.building_id = b.building_id\n\nWHERE\n  b.site_id = 3\nGROUP BY\n  date_trunc('hour', sd.timestamp), b.site_id\nORDER BY\n  \"time\";\n"
    }
   ]
  },
  {
   "title": "average consumption for area 4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  date_trunc('hour', sd.timestamp) AS \"time\",\n  AVG(sd.meter_reading) AS \"Total Consumption\"\nFROM\n  sensor_data sd\nJOIN\n  buildings b ON sd.building_id = b.building_id\nWHERE\n  b.site_id = 4\nGROUP BY\n  date_trunc('hour', sd.timestamp), b.site_id\nORDER BY\n  \"time\";\n"
    }
   ]
  }
 ]
}